module.exports = {
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    CORPORATION_ADMIN: 'CORPORATION_ADMIN',
    WARD_ADMIN: 'WARD_ADMIN',
    CORPORATOR: 'CORPORATOR',
    DEPARTMENT_HEAD: 'DEPARTMENT_HEAD',
    OFFICER: 'OFFICER',
    STAFF: 'STAFF',
    CONTRACTOR: 'CONTRACTOR',
    CITIZEN: 'CITIZEN',
    PUBLIC_USER: 'PUBLIC_USER'
  },
  COMPLAINT_STATUS: {
    REGISTERED: 'REGISTERED',
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    INSPECTION: 'INSPECTION',
    RESOLVED: 'RESOLVED',
    CITIZEN_VERIFICATION: 'CITIZEN_VERIFICATION',
    CLOSED: 'CLOSED',
    REOPENED: 'REOPENED',
    ESCALATED: 'ESCALATED'
  },
  WORK_STATUS: {
    PROPOSED: 'PROPOSED',
    APPROVED: 'APPROVED',
    TENDERED: 'TENDERED',
    WORK_ORDER_ISSUED: 'WORK_ORDER_ISSUED',
    NOT_STARTED: 'NOT_STARTED',
    ONGOING: 'ONGOING',
    DELAYED: 'DELAYED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  }
};
